In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
p = [1096.95, 560.94, 896.95]

In [3]:
c = 30.1

In [5]:
prices =np.array(p)

In [6]:
prices

array([1096.95,  560.94,  896.95])

In [7]:
prices * c

array([33018.195, 16884.294, 26998.195])

# 加權

In [8]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [9]:
grade = np.array([85, 70, 82])

In [10]:
weights = np.array([0.3, 0.4, 0.3])

In [11]:
g = grade * weights

In [12]:
g

array([25.5, 28. , 24.6])

In [13]:
g.sum()

78.1

In [14]:
np.dot(grade, weights)

78.1